name: pinput_plus
description: A customizable PIN/OTP input widget for Flutter.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

repository: https://github.com/thamerhussain/pinput_plus
homepage: https://github.com/thamerhussain/pinput_plus
topics:
  - pin
  - otp
  - input
  - flutter

