name: pinput_plus
description: Flexible, customizable PIN/OTP input for Flutter with themes, masking, and validation—ideal for login, 2FA, and verification flows on mobile, desktop and web.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  uses-material-design: false

repository: https://github.com/thamerhussain/pinput_plus
homepage: https://github.com/thamerhussain/pinput_plus
topics:
  - pin
  - otp
  - input
  - flutter

